### ISSUE TITLE
unmounting inactive tab and mounting only when active 

### ISSUE THREAD

**Issue by vijaymotupalli** [themre/react-closeable-tabs#3]
create multiple tabs and now try changing tabs from one tab to another ,each time you change tab that tab mounting again.

**Comment by themre** [comment]
yes, that's the purpose of React, to clean up DOM after you don't use that component. I can add a prop to toggle CSS visibility instead of unmounting. but you will need to be careful not to have too many tabs open. would this be better?

**Comment by vijaymotupalli** [comment]
that would be better because some times we dont want to unmount even not used.
as you said extra prop based on that you can hide remaining doms and show only active dom .
thanks for the quick reply.

**Comment by themre** [comment]
ok I'll try to push new version.

**Comment by vijaymotupalli** [comment]
thanks!

**Comment by themre** [comment]
since I haven't touched this lib for a while, I bumped dependencies to latest stable version (react@16.6.3 and SC@4.1.2) and released version 1.1.1.
now for this feature I added prop `noTabUnmount` which controls tab visibility only with CSS so components are not unmounted. 
demo can be viewed here: https://codesandbox.io/s/84w2n68l98

**Comment by vijaymotupalli** [comment]
thanks!
